#!/bin/sh
if [ "X$1" = X ]; then
	echo usage: svc-waitdown service
	exit 1
fi
if svc-isdown "$1"; then exit 0; fi
sleep 1
count=1
while svc-isup "$1"; do
  echo -n .
  sleep 1
  let count=count+1
  if [ $count -gt ${SVCTIMEOUT-15} ]; then exit 1; fi
done
