#!/bin/sh
set -e
if [ "X$1" = X ]; then
	echo "usage: svc-start service [program [args...]]"
	exit 1
fi
svc="$1"
shift

echo -n "Starting $svc: "

cd "${SVSCANDIR-/var/service}"

if [ ! -f /var/run/svscan.pid ]; then
  echo " svscan is not running; this service cannot be started now."
  exit 1
fi

if [ ! -d "$svc" ]; then
  # Make sure that the symlink for svscan exists
  rm -f "$svc"
  ln -s "${SVCLOCKDIR-/var/lock/svc}/$svc" "$svc"
fi

start() {
  # Check the "run" file
  if [ ! -e "$1/run" ]; then
    echo " run file does not exist!"
    exit 1
  fi

  rm -f "$1/down"

  if svok "$1"; then
    svc -u "$1"
    svc-waitup "$1"
    echo -n " $1"
  else
    echo -n " $1 (will be started later)"
  fi
}

# Control the log process first, so that all messages are logged ...
if [ -d "$svc/log" ]; then
  chmod +t "$svc"
  start "$svc/log"
fi

# ... and then the main process.
start "$svc"

echo " done."
