#!/bin/sh
PATH=/usr/local/bin:/sbin:/usr/sbin:/usr/bin:/bin
exec </dev/console
exec >/dev/console 2>&1
cd "${1-/service}"
for svc in *
do
  svok "$svc/log" && svc -dx "$svc/log"
  svok "$svc" && svc -dx "$svc"
done
