#!/bin/sh
set -e

# Set up variables for the input file, a backup copy of the inittab, and
# a temporary output file.

filename="${1-/etc/inittab}"

backup="$filename~"
if [ -e "$backup" ]
then
  echo "$0: Backup file '$backup' already exists."
  exit 1;
fi

tmpfile="${filename}.tmp"
if [ -e "$tmpfile" ]
then
  echo "$0: Temporary file '$tmpfile' already exists."
  exit 1
fi

# Look for the magic "rc" lines in the inittab

if grep '^SV:.*svscan-start' "$filename" >/dev/null 2>&1 || \
   grep '^SX:.*svscan-stopall' "$filename" >/dev/null 2>&1
then
  echo "$0: '$filename' appears to already have the svscan lines in it."
  exit 0
fi

lineno=`grep -n '^[^:]*:0:wait:.*rc' "$filename" | cut -d: -f1`
if [ -z "$lineno" ]
then
  echo "$0: Couldn't find the first 'rc' line in '$filename'."
  exit 1;
fi

# Insert the two svscan lines between the first rc line and the rest of
# the inittab so that svscan gets executed before the rc# scripts do.

if ! touch "$tmpfile" >/dev/null 2>&1
then
  echo "$0: Could not create the temporary output file '$tmpfile'"
  exit 1
fi

{
  let lineno=lineno-1
  head -$lineno "$filename"
  echo "SV:2345:respawn:/usr/bin/svscan-start /service"
  echo "SX:S016:wait:/usr/bin/svscan-stopall /service"
  echo
  let lineno=lineno+1
  tail +$lineno "$filename"
} >"$tmpfile"

# Finally, safely move the new inittab over the old one.
ln "$filename" "$backup"
mv -f "$tmpfile" "$filename"
